const CONFIG = {
    introTitle: 'Babe à!',
    introDesc: `Nếu anh không phiền thì làm ngiu em nhé 😋`,
    btnIntro: 'Bấm dô đây nề !',
    title: 'Phải chăng anh đã yêu ngay từ cái nhìn đầu tiên 😙',
    desc: 'Phải chăng anh đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'Hơi bị thích emm <33',
    btnNo: 'Không, Em gái à 😏',
    question:'Trên thế giới hơn 7 tỉ người mà sao Đức lại yêu Tú dạaa 🥺❤️',
    btnReply: 'Gửi cho tuii nah <3',
    reply: 'Yêu thì yêu mà không yêu thì mãi yêu <33333333',
    mess: 'Emm biết mà 🥰. Yêu Đức nhiều nhiều 😘😘',
    messDesc: 'Em yêu anh nhiềuuuuuuu.',
    btnAccept: 'Mãi yêu anh <3',
    messLink: 'https://www.facebook.com/anhaa285' 
