const CONFIG = {
    introTitle: 'chào bạn mình là Ngọc Thư hehehehe',
    introDesc: `rảnh quá bấm zô chi vậy`,
    btnIntro: 'hihihihihihihihihi ',
    title: 'mình chỉ muốn nói là mình hận bạn',
    desc: 'bít tại sao hơm',
    btnYes: 'còn lâu mới nói',
    btnNo: 'yêu Ngọc Thư',
    question:'mình có dễ thương hơm',
    btnReply: 't hận m 🥲',
    reply: 'được ời bạn tuyệt vời lắm hãy luôn zui zẻ nha',
    mess: 'mình sẽ zui zẻ iu bạn 🥰',
    messDesc: 'Tối nay bạn ngủ ngon 😴😴😴',
    btnAccept: 'cảm ơn Ngthuw iu Ngthuw',
  
